# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-12-21 10:16:56
"""
import arcpy
def #  NOT  IMPLEMENTED# Function Body not implemented

def jsonTofeatures():  # json to features

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    _20212012_json = "\\\\emcgis\\nas\\GISDATA\\Workgroups\\GISPlanning\\Transportation_Projects\\TV_HWY\\Data\\ODOT\\20212012_json"

    for File_json, Name in #  NOT  IMPLEMENTED(_20212012_json, "*", "json", "NOT_RECURSIVE"):

        # Process: JSON To Features (JSON To Features) (conversion)
        Name = "FX_PC_STIP_2427_20212012"
        _Name_ = fr"\\emcgis\nas\GISDATA\Workgroups\GISPlanning\Transportation_Projects\TV_HWY\Data\ODOT\Test\test.gdb\{Name}"
        arcpy.conversion.JSONToFeatures(in_json_file=File_json, out_features=_Name_, geometry_type="POLYGON")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"\\emcgis\nas\GISDATA\Workgroups\GISWebTeam\APRXs\LUT_PDS\TV_HWY\TV_HWY.gdb", workspace=r"\\emcgis\nas\GISDATA\Workgroups\GISWebTeam\APRXs\LUT_PDS\TV_HWY\TV_HWY.gdb"):
        jsonTofeatures()