# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# THPRD_SDC_Update2.py
# Created on: 2019-12-03 16:01:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
distribution_BOUNDARY_thprd_sdc = "Database Connections\\zWRITE.washsde.Distribution.Boundary.sde\\distribution.BOUNDARY.thprd_sdc"
distribution_BOUNDARY_thprd_sdc__2_ = distribution_BOUNDARY_thprd_sdc
production_BOUNDARY_thprd_sdc = "production.BOUNDARY.thprd_sdc"
production_BOUNDARY_thprd_sdc_Selection = production_BOUNDARY_thprd_sdc
distribution_BOUNDARY_thprd_sdc_updated = production_BOUNDARY_thprd_sdc_Selection
distribution_BOUNDARY_thprd_sdc_Truncated = "Database Connections\\zWRITE.washsde.Distribution.Boundary.sde\\distribution.BOUNDARY.thprd_sdc"

# Process: Truncate Table
arcpy.TruncateTable_management(distribution_BOUNDARY_thprd_sdc)

# Process: Select Layer By Attribute
arcpy.SelectLayerByAttribute_management(production_BOUNDARY_thprd_sdc, "NEW_SELECTION", "EffDate <= GETDATE()")

# Process: Append
arcpy.Append_management("production.BOUNDARY.thprd_sdc", distribution_BOUNDARY_thprd_sdc_Truncated, "NO_TEST", "RECDIST \"RECDIST\" true true false 6 Text 0 0 ,First,#,production.BOUNDARY.thprd_sdc,RECDIST,-1,-1;SDC \"SDC\" true true false 255 Text 0 0 ,First,#,production.BOUNDARY.thprd_sdc,SDC,-1,-1;Name \"Name\" true true false 255 Text 0 0 ,First,#,production.BOUNDARY.thprd_sdc,Name,-1,-1;Note \"Note\" true true false 255 Text 0 0 ,First,#,production.BOUNDARY.thprd_sdc,Note,-1,-1;Ordinance \"Ordinance\" true true false 10 Text 0 0 ,First,#,production.BOUNDARY.thprd_sdc,Ordinance,-1,-1;Shape.STArea() \"Shape.STArea()\" false false true 0 Double 0 0 ,First,#,production.BOUNDARY.thprd_sdc,Shape.STArea(),-1,-1;Shape.STLength() \"Shape.STLength()\" false false true 0 Double 0 0 ,First,#,production.BOUNDARY.thprd_sdc,Shape.STLength(),-1,-1", "")

