# ---------------------------------------------------------------------------
# Accel_IRISlines_update.py
# Created on: 2016-01-28
#   (generated by ArcGIS/ModelBuilder) 10.2.1
# Description:  Pulls data from milepost data and aggregates into usable segments for Accela.
# ---------------------------------------------------------------------------

#Allows importing of custom modules
import os, sys
cmd_folder = "\\\\emcgis\\nas\\LUTOPS\\GIS\\Production\\python\\CommonModules\\"
if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)

# Import arcpy module
import arcpy
from arcpy import env

# Import custom modules
import gbl, trktime
from DataTransfer.modMoveData import  GISAppendFeatures, GISTruncate

from modEmail import Send


Title = "Accela IRIS Update log"
Message = ""
Error = 0
EmailTo = gbl.MyEmail
ScrptTimer = trktime.stopwatch()

try:

# Process: Clear Workspace Cache
    arcpy.ClearWorkspaceCache_management("")

    print "Delete features from production"
    Temp = GISTruncate(gbl.NpSTREETS+gbl.lrs_IRIS_allMP_lines_coarse_Accela)
    Message = Message + Temp.appendMessage
    Error = Error + Temp.fail

    print "Append features to production"
    Temp = GISAppendFeatures(gbl.NpSTREETS+gbl.LRS_IRIS_ALLMP_LINES_COARSE_Step1, gbl.NpSTREETS+gbl.lrs_IRIS_allMP_lines_coarse_Accela)
    Message = Message + Temp.appendMessage
    Error = Error + Temp.fail

    AccelaLines="\\\\emcgis\\nas\\LUTOPS\\GIS\\Production\\Transpor\\EventThemes\\required\\AllMPAccela.lyr"
    RemoveFromAccelaLines="\\\\emcgis\\nas\\LUTOPS\\GIS\\Production\\Transpor\\EventThemes\\required\\RemoveNotWashCo.lyr"

    arcpy.MakeFeatureLayer_management(AccelaLines, "lyrAccelaLines")

    arcpy.MakeFeatureLayer_management(RemoveFromAccelaLines, "lyrRemoveFromAccelaLines")

    arcpy.SelectLayerByLocation_management("lyrAccelaLines","SHARE_A_LINE_SEGMENT_WITH","lyrRemoveFromAccelaLines","","NEW_SELECTION")

    arcpy.DeleteFeatures_management("lyrAccelaLines")

    if int(arcpy.GetCount_management(gbl.NpSTREETS+gbl.lrs_IRIS_allMP_lines_coarse_Accela).getOutput(0))>20000:


        print "Delete features from distribution"
        Temp = GISTruncate(gbl.NdSTREETS+gbl.lrs_IRIS_allMP_lines_coarse_Accela)
        Message = Message + Temp.appendMessage
        Error = Error + Temp.fail


        print "Append features to distribution"
        Temp = GISAppendFeatures(gbl.NpSTREETS+gbl.lrs_IRIS_allMP_lines_coarse_Accela,gbl.NdSTREETS+gbl.lrs_IRIS_allMP_lines_coarse_Accela)
        Message = Message + Temp.appendMessage
        Error = Error + Temp.fail
    else:
        Error=Error+1
        Message=Message+'/n More road segments expected. Push to distribution did not run.'


#Adds a final script time to email
    TtlScrptTime = ScrptTimer.Stop()
    Message = Message + "Total processing time : " + TtlScrptTime + " seconds."

    print "All Done!!!"

# Send email with successful operations
    Send(Title, Message, Error, EmailTo)

except:  #send email with errors

    EmailTo #+ ",Wayne_Flynn@co.washington.or.us,Richard_Crucchiola@co.washington.or.us"
    Error = Error + 1
    Message = Message + arcpy.GetMessages()
    Message = Message + "\n" + str(sys.exc_info()[0]) + "\n" + str(sys.exc_info()[1]) + "\n" + str(sys.exc_info()[2])

    Send(Title, Message, Error, EmailTo)
